trigger: none

pool:
  name: 'MyLocalAgentPool'

variables:
  dotNetVersion: '9.0.200'
  project: 'backend/src/Functions/Azure/FileTransfer/FileTransfer.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  functionApp: 'func-vista-filetransfer-dev-001'
  subscription: 'MyAzureSubscription(19a97b41-e18f-481b-a072-dba7985b27bd)'

steps:
  - checkout: self
    displayName: 'Checkout'
    clean: true
    fetchDepth: 1

  - task: NuGetToolInstaller@1

  - task: UseDotNet@2
    displayName: 'Use .NET $(dotNetVersion)'
    inputs:
      version: $(dotNetVersion)

  - task: DotNetCoreCLI@2
    displayName: 'Publish FileTransfer'
    inputs:
      command: 'publish'
      feedsToUse: 'select'
      verbosityRestore: 'Normal'
      publishWebProjects: false
      projects: '$(project)'
      modifyOutputPath: false
      configuration: '$(buildConfiguration)'

  - task: AzureFunctionApp@2
    displayName: 'Azure Function Deployment'
    inputs:
      connectedServiceNameARM: '$(subscription)'
      appType: 'functionApp'
      appName: '$(functionApp)'
      package: '$(Build.ArtifactStagingDirectory)/publish.zip'
      deploymentMethod: 'zipDeploy'