trigger: none

pool:
  name: 'MyLocalAgentPool'

variables:
  dotNetVersion: '9.0.101'
  solution: './backend/Vista.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
  - task: CmdLine@2
    displayName: 'Docker login'
    inputs:
      script: 'echo $(GITHUB_TOKEN) | docker login ghcr.io -u Lemao81 --password-stdin'

  - task: NuGetToolInstaller@1
    displayName: 'Install NuGet'

  - task: UseDotNet@2
    displayName: 'Use .NET $(dotNetVersion)'
    inputs:
      version: $(dotNetVersion)

  - task: NuGetCommand@2
    displayName: 'Restore'
    inputs:
      command: 'restore'
      restoreSolution: '$(solution)'
      feedsToUse: 'select'
      verbosityRestore: 'Normal'
      arguments: '-MSBuildPath C:\MyLocalAgent\_work\_tool\dotnet\sdk\9.0.102'

  - task: DotNetCoreCLI@2
    displayName: 'Build'
    inputs:
      command: 'build'
      projects: '$(solution)'
      arguments: '--no-restore'
      configuration: '$(buildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: 'Test'
    inputs:
      command: 'test'
      projects: '$(solution)'
      arguments: '--no-restore --no-build'
      configuration: '$(buildConfiguration)'
