trigger: none

pool:
  name: 'MyLocalAgentPool'

variables:
  dotNetVersion: '9.0.200'
  solution: './backend/Vista.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
  - task: NuGetToolInstaller@1

  - task: UseDotNet@2
    displayName: 'Use .NET $(dotNetVersion)'
    inputs:
      version: $(dotNetVersion)

  - task: NuGetCommand@2
    displayName: 'Restore'
    inputs:
      command: 'restore'
      restoreSolution: '$(solution)'
      feedsToUse: 'select'
      verbosityRestore: 'Normal'

  - task: DotNetCoreCLI@2
    displayName: 'Publish FileTransfer'
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: './backend/src/Functions/Azure/FileTransfer/FileTransfer.csproj'
      arguments: '--no-restore'
      modifyOutputPath: false
      configuration: '$(buildConfiguration)'