trigger: none

pool:
  name: 'MyLocalAgentPool'

variables:
  dotNetVersion: '9.0.200'
  project: 'backend/src/Functions/Azure/FileTransfer/FileTransfer.csproj'
  solution: './backend/Vista.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
  - task: NuGetToolInstaller@1

  - task: UseDotNet@2
    displayName: 'Use .NET $(dotNetVersion)'
    inputs:
      version: $(dotNetVersion)

  - task: DotNetCoreCLI@2
    displayName: 'Publish FileTransfer'
    inputs:
      command: 'publish'
      feedsToUse: 'select'
      verbosityRestore: 'Normal'
      publishWebProjects: false
      projects: '$(project)'
      modifyOutputPath: false
      configuration: '$(buildConfiguration)'