trigger:
  - main

pool:
  name: 'MyLocalAgentPool'

variables:
  dotNetVersion: '9.0.200'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  solution: './backend/Vista.sln'
  subscription: 'MyAzureSubscription(19a97b41-e18f-481b-a072-dba7985b27bd)'
  identityClientId: '3e7123ab-9eca-43bc-ae2c-6405047676fd'

steps:
  - checkout: self
    displayName: 'Checkout'
    clean: true
    fetchDepth: 1
    
  - task: AzureCLI@2
    displayName: 'Azure login'
    inputs:
      azureSubscription: '$(subscription)'
      scriptType: 'ps'
      scriptLocation: 'inlineScript'
      inlineScript: 'az login --service-principal --username $(AZ_USERNAME) --password $(AZ_PASSWORD) --tenant $(AZ_TENANT_ID) --debug'

  - task: NuGetToolInstaller@1

  - task: UseDotNet@2
    displayName: 'Use .NET $(dotNetVersion)'
    inputs:
      version: $(dotNetVersion)

  - task: NuGetCommand@2
    displayName: 'Restore'
    inputs:
      command: 'restore'
      restoreSolution: '$(solution)'
      feedsToUse: 'select'
      verbosityRestore: 'Normal'

  - task: DotNetCoreCLI@2
    displayName: 'Build'
    inputs:
      command: 'build'
      projects: '$(solution)'
      arguments: '--no-restore'
      configuration: '$(buildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: 'Test'
    inputs:
      command: 'test'
      projects: '$(solution)'
      arguments: '--no-restore --no-build'
      configuration: '$(buildConfiguration)'
