trigger: none

pool:
  name: 'MyLocalAgentPool'

variables:
  dotNetVersion: '9.0.200'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  webProject: 'backend/src/Services/Maintenance/WebApi/WebApi.csproj'
  functionsProject: 'backend/src/Functions/Azure/FileTransfer/FileTransfer.csproj'
  subscription: 'MyAzureSubscription(19a97b41-e18f-481b-a072-dba7985b27bd)'
  webApp: 'app-vista-maintenance-dev-001'
  functionsApp: 'func-vista-filetransfer-dev-001'

steps:
  - checkout: self
    displayName: 'Checkout'
    clean: true
    fetchDepth: 1

  - task: NuGetToolInstaller@1

  - task: UseDotNet@2
    displayName: 'Use .NET $(dotNetVersion)'
    inputs:
      version: $(dotNetVersion)

  - task: DotNetCoreCLI@2
    displayName: 'Publish Maintenance'
    inputs:
      command: 'publish'
      feedsToUse: 'select'
      verbosityRestore: 'Normal'
      publishWebProjects: false
      projects: '$(webProject)'
      modifyOutputPath: false
      configuration: '$(buildConfiguration)'

  - task: AzureWebApp@1
    displayName: 'Web App Deployment'
    inputs:
      azureSubscription: '$(subscription)'
      appType: 'webAppLinux'
      appName: '$(webApp)'
      package: '$(Build.SourcesDirectory)/**/Maintenance/**/publish.zip'

  - task: DotNetCoreCLI@2
    displayName: 'Publish FileTransfer'
    inputs:
      command: 'publish'
      feedsToUse: 'select'
      verbosityRestore: 'Normal'
      publishWebProjects: false
      projects: '$(functionsProject)'
      modifyOutputPath: false
      configuration: '$(buildConfiguration)'

  - task: AzureFunctionApp@2
    displayName: 'Azure Function Deployment'
    inputs:
      connectedServiceNameARM: '$(subscription)'
      appType: 'functionApp'
      appName: '$(functionsApp)'
      package: '$(Build.SourcesDirectory)/**/FileTransfer/**/publish.zip'
      deploymentMethod: 'zipDeploy'
