services:
  vista-postgres:
    build:
      context: ./deployment/docker/postgres
      dockerfile: ./Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
      PGUSER: ${DB_USER}
    volumes:
      - "vista-postgres-data:/var/lib/postgresql/data/"
    secrets:
      - postgres-password
    networks:
      vista:
        aliases:
          - postgres
  
  vista-file-transfer-api:
    build:
      context: .
      dockerfile: src/Services/FileTransfer/WebApi/Dockerfile
    networks:
      vista:
        aliases:
          - file-transfer-api

volumes:
  vista-postgres-data:
    
secrets:
  postgres-password:
    file: postgres-password

networks:
  vista:
    driver: bridge