version: "3.9"

services:
  vista-postgres:
    build:
      context: ./deployment/docker/postgres
      dockerfile: ./Dockerfile
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
      PGUSER: ${DB_USER}
    volumes:
      - "vista-postgres-data:/var/lib/postgresql/data/"
    secrets:
      - postgres-password
    ports:
      - "5432:5432"
    networks:
      vista:
        aliases:
          - postgres
  
  vista-minio:
    build:
      context: ./deployment/docker/minio
      dockerfile: ./Dockerfile
    env_file:
      - .env.secrets
    volumes:
      - "vista-minio-data:/data"
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      vista:
        aliases:
          - minio
  
  vista-maintenance-api:
    build:
      context: .
      dockerfile: src/Services/Maintenance/WebApi/Dockerfile
      args:
        DOTNET_VERSION: ${DOTNET_VERSION}
    environment:
      Database__Host: ${DB_HOST}
      Database__Username: ${DB_USER}
      Database__PasswordFile: /run/secrets/postgres-password
      Minio__KeysFile: /run/secrets/minio-keys
    secrets:
      - postgres-password
      - minio-keys
    ports:
      - "5001:8080"
    depends_on:
      vista-postgres:
        condition: service_healthy
      vista-minio:
        condition: service_healthy
    networks:
      vista:
        aliases:
          - maintenance-api
  
  vista-file-transfer-api:
    build:
      context: .
      dockerfile: src/Services/FileTransfer/WebApi/Dockerfile
      args:
        DOTNET_VERSION: ${DOTNET_VERSION}
    environment:
      Database__Host: ${DB_HOST}
      Database__Username: ${DB_USER}
      Database__PasswordFile: /run/secrets/postgres-password
      Minio__KeysFile: /run/secrets/minio-keys
    secrets:
      - postgres-password
      - minio-keys
    ports:
      - "5000:8080"
    depends_on:
      vista-maintenance-api:
        condition: service_healthy
    networks:
      vista:
        aliases:
          - file-transfer-api

  vista-seq:
    environment:
      - ACCEPT_EULA=Y
      - memory=1g
      - memory-swap=1g
    image: datalust/seq:2024.3.13181
    ports:
      - "5341:5341"
      - "5342:80"
    networks:
      vista:
        aliases:
          - seq
  
  vista-aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    ports:
      - "18888:18888"
      - "4317:18889"
    networks:
      vista:
        aliases:
          - aspire-dashboard

volumes:
  vista-postgres-data:
  vista-minio-data:

secrets:
  postgres-password:
    file: postgres-password
  minio-keys:
    file: minio-keys

networks:
  vista:
    driver: bridge