version: "3.9"

services:
  vista-seq:
    environment:
      - ACCEPT_EULA=Y
      - memory=1g
      - memory-swap=1g
    image: datalust/seq:2024.3.13181
    ports:
      - "5341:5341"
      - "5342:80"
    networks:
      vista:
        aliases:
          - seq
  
  vista-postgres:
    build:
      context: ./deployment/docker/postgres
      dockerfile: ./Dockerfile
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
      PGUSER: ${DB_USER}
    volumes:
      - "vista-postgres-data:/var/lib/postgresql/data/"
    secrets:
      - postgres-password
    ports:
      - "5432:5432"
    networks:
      vista:
        aliases:
          - postgres
  
  vista-file-transfer-api:
    build:
      context: .
      dockerfile: src/Services/FileTransfer/WebApi/Dockerfile
    environment:
      Database__Host: ${DB_HOST}
      Database__Username: ${DB_USER}
      Database__PasswordFile: /run/secrets/postgres-password
    secrets:
      - postgres-password
    ports:
      - "5000:8080"
    networks:
      vista:
        aliases:
          - file-transfer-api

volumes:
  vista-postgres-data:

secrets:
  postgres-password:
    file: postgres-password

networks:
  vista:
    driver: bridge