trigger:
  - main

pool:
  name: 'MyLocalAgentPool'

variables:
  dotNetVersion: '9.0.101'
  solution: './backend/Vista.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
  - task: NuGetToolInstaller@1

  - task: UseDotNet@2
    displayName: 'Use .NET $(dotNetVersion)'
    inputs:
      version: $(dotNetVersion)

  - task: NuGetCommand@2
    displayName: 'Restore'
    inputs:
      command: 'restore'
      restoreSolution: '$(solution)'
      feedsToUse: 'select'
      verbosityRestore: 'Normal'

  - task: DotNetCoreCLI@2
    displayName: 'Build'
    inputs:
      command: 'build'
      projects: '$(solution)'
      arguments: '--no-restore'
      configuration: '$(buildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: 'Test'
    inputs:
      command: 'test'
      projects: '$(solution)'
      arguments: '--no-restore --no-build'
      configuration: '$(buildConfiguration)'
