trigger: none

pool:
  name: 'MyLocalAgentPool'

variables:
  dotNetVersion: '9.0.200'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  subscription: 'MyAzureSubscription(19a97b41-e18f-481b-a072-dba7985b27bd)'
  maintenanceProject: 'backend/src/Services/Maintenance/WebApi/WebApi.csproj'
  maintenanceApp: 'app-vista-maintenance-dev-001'
  maintenancePackage: '$(Build.SourcesDirectory)/**/Maintenance/**/publish.zip'
  functionsProject: 'backend/src/Functions/Azure/FileTransfer/FileTransfer.csproj'
  functionsApp: 'func-vista-filetransfer-dev-001'
  functionsPackage: '$(Build.SourcesDirectory)/**/FileTransfer/**/publish.zip'

steps:
  - checkout: self
    displayName: 'Checkout'
    clean: true
    fetchDepth: 1

  - task: NuGetToolInstaller@1

  - task: UseDotNet@2
    displayName: 'Use .NET $(dotNetVersion)'
    inputs:
      version: $(dotNetVersion)

  - task: DotNetCoreCLI@2
    displayName: 'Publish Maintenance'
    inputs:
      command: 'publish'
      feedsToUse: 'select'
      verbosityRestore: 'Normal'
      publishWebProjects: false
      projects: '$(maintenanceProject)'
      modifyOutputPath: false
      configuration: '$(buildConfiguration)'

  - task: AzureWebApp@1
    displayName: 'Deploy Maintenance'
    inputs:
      azureSubscription: '$(subscription)'
      appType: 'webAppLinux'
      appName: '$(maintenanceApp)'
      package: '$(maintenancePackage)'

  - task: DotNetCoreCLI@2
    displayName: 'Publish Functions'
    inputs:
      command: 'publish'
      feedsToUse: 'select'
      verbosityRestore: 'Normal'
      publishWebProjects: false
      projects: '$(functionsProject)'
      modifyOutputPath: false
      configuration: '$(buildConfiguration)'

  - task: AzureFunctionApp@2
    displayName: 'Deploy Functions'
    inputs:
      connectedServiceNameARM: '$(subscription)'
      appType: 'functionApp'
      appName: '$(functionsApp)'
      package: '$(functionsPackage)'
      deploymentMethod: 'runFromPackage'
