trigger: none

pool:
  name: 'MyLocalAgentPool'

variables:
  dotNetVersion: '10.0.103'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  subscription: 'MyAzureSubscription(19a97b41-e18f-481b-a072-dba7985b27bd)'
  functionsProject: 'backend/src/Functions/Azure/FileTransfer/FileTransfer.csproj'
  functionsApp: 'func-vista-filetransfer-dev-001'
  functionsPackage: '$(Build.SourcesDirectory)/**/FileTransfer/**/publish.zip'

steps:
  - checkout: self
    displayName: 'Checkout'
    clean: true
    fetchDepth: 1

  - task: NuGetToolInstaller@1

  - task: UseDotNet@2
    displayName: 'Use .NET $(dotNetVersion)'
    inputs:
      version: $(dotNetVersion)

  - task: DotNetCoreCLI@2
    displayName: 'Publish Functions'
    inputs:
      command: 'publish'
      feedsToUse: 'select'
      verbosityRestore: 'Normal'
      publishWebProjects: false
      projects: '$(functionsProject)'
      modifyOutputPath: false
      configuration: '$(buildConfiguration)'

  - task: AzureFunctionApp@2
    displayName: 'Deploy Functions'
    inputs:
      connectedServiceNameARM: '$(subscription)'
      appType: 'functionApp'
      appName: '$(functionsApp)'
      package: '$(functionsPackage)'
      deploymentMethod: 'runFromPackage'
