trigger: none

pool:
  name: 'MyLocalAgentPool'

variables:
  subscription: 'VistaAppDevelopmentServiceConnection'
  environment: 'dev'
  location: 'centralus'
  suffix: ''
  dotNetVersion: '10.0.103'
  maintenanceProject: 'backend/src/Services/Maintenance/WebApi/WebApi.csproj'
  maintenanceApp: 'app-vista-maintenance-$(environment)-$(location)-$(suffix)'
  maintenancePackage: '$(Build.SourcesDirectory)/**/Maintenance/**/publish.zip'
  buildConfiguration: 'Release'
  buildPlatform: 'Any CPU'

steps:
  - checkout: self
    displayName: 'Checkout'
    clean: true
    fetchDepth: 1

  - task: NuGetToolInstaller@1

  - task: UseDotNet@2
    displayName: 'Use .NET $(dotNetVersion)'
    inputs:
      version: $(dotNetVersion)

  - task: DotNetCoreCLI@2
    displayName: 'Publish Maintenance'
    inputs:
      command: 'publish'
      feedsToUse: 'select'
      verbosityRestore: 'Normal'
      publishWebProjects: false
      projects: '$(maintenanceProject)'
      modifyOutputPath: false
      configuration: '$(buildConfiguration)'

  - task: AzureWebApp@1
    displayName: 'Deploy Maintenance'
    inputs:
      azureSubscription: '$(subscription)'
      appType: 'webAppLinux'
      appName: '$(maintenanceApp)'
      package: '$(maintenancePackage)'