name: Docker image build

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: lemao81/vista-maintenance-api

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  build_and_push:
    name: Build and push
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/src/Services/Maintenance/WebApi/Dockerfile
          push: true
          tags: latest